name: Publish
on:
  release:
    types: [created]

jobs:

  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Upload to Docker
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jib -Pdocker=jitstrategies
        env:
          DOCKER_KEY: ${{ secrets.DOCKERHUB_PAT }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
      - name: Build zip
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: distZip
      - name: Upload Release
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./build/distributions/*.zip
          file_glob: true